import { collection, getDoc, where, query, getDocs } from "firebase/firestore"
import Head from "next/head"
import { useEffect } from "react"
import { useDispatch, useSelector } from "react-redux"
import AdminLayout from "../../../components/layouts/admin/AdminLayout"
import Heading from "../../../components/pages/admin/Heading"
import { useRouter } from "next/router"
import { db } from "../../../firebase.config"
import { addCourseDetail } from "../../../redux/slice/adminCourseSlice"
import CourseDetail from "../../../components/pages/admin/course/CourseDetail"

function Course() {
    const { trigger } = useSelector((sta) => sta.adminCourse)
    const dispatch = useDispatch()

    const router = useRouter()

    useEffect(() => {
        async function getCourseDetail() {
            try {
                const slug = router.query.id
                const q = query(
                    collection(db, "courses"),
                    where("slug", "==", slug)
                )
                const result = await getDocs(q)
                if (result.docs.length > 0) {
                    const doc = result.docs[0]
                    const courseDoc = { _id: doc.id, ...doc.data() }
                    const categoryRef = doc.data().categoryId
                    await getDoc(categoryRef).then((cate) => {
                        courseDoc.category = { ...cate.data() }
                    })
                    dispatch(addCourseDetail(courseDoc))
                }
            } catch (error) {
                console.log(error)
            }
        }
        getCourseDetail()
    }, [trigger, dispatch])

    return (
        <>
            <Head>
                <title>
                    Khóa học | Tridev.io - Học lập trình miễn phí | Học lập
                    trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
            <Heading lv1='Quản lý khóa học' />
            <CourseDetail />
        </>
    )
}

Course.getLayout = function getLayout(page) {
    return <AdminLayout>{page}</AdminLayout>
}

export default Course
