import { useRouter } from "next/router"
import React, { useEffect } from "react"
import Head from "next/head"

const Index = () => {
    const router = useRouter()
    useEffect(() => {
        if (router.pathname === "/admin") {
            router.push("/admin/dashboard")
        }
    }, [router])

    return (
        <>
            <Head>
                <title>
                    Quản trị - Học lập trình miễn phí | Học lập trình Javascript
                    | Học lập trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
        </>
    )
}

Index.getLayout = function getLayout(page) {
    return <>{page}</>
}

export default Index
