import { Box, Container, Grid, GridItem, Heading } from '@chakra-ui/react'
import Head from 'next/head'
import CartCheckOut from '../components/pages/cart/CartCheckOut'
import CartList from '../components/pages/cart/CartList'

const cart = () => {
    return (
        <div>
            <Head>
                <title>
                    Giỏ hàng - Học lập trình miễn phí | Học lập trình Javascript
                    | Học lập trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>

            <Box py='8' minH='calc(100vh - 350px)'>
                <Container maxW={[1024]}>
                    <Heading as='h1'>Giỏ hàng</Heading>
                    <Grid gridTemplateColumns='repeat(12, 1fr)' my='4' gap='4'>
                        <GridItem
                            colSpan='12'
                            display={{ base: 'block', md: 'none' }}
                        >
                            <CartCheckOut />
                        </GridItem>
                        <GridItem colSpan={['12', '12', '8']}>
                            <CartList />
                        </GridItem>
                        <GridItem
                            colSpan={['12', '12', '4']}
                            display={{ base: 'none', md: 'block' }}
                        >
                            <CartCheckOut />
                        </GridItem>
                    </Grid>
                </Container>
            </Box>
        </div>
    )
}

export default cart
