import Head from 'next/head'
import CreateModel from '../components/pages/admin/category/CreateModel'
import Banner from '../components/pages/home/Banner'
import CatelogySection from '../components/pages/home/CatelogySection'
import CatelogyTab from '../components/pages/home/CatelogyTab'
import CourseSection from '../components/pages/home/CourseSection'
import FeatureSection from '../components/pages/home/FeatureSection'

export default function Home() {
	return (
		<div>
			<Head>
				<title>
					Tridev.io - Học lập trình miễn phí | Học lập trình
					Javascript | Học lập trình cho người mới
				</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' type='image/png' href='/code.png' />
			</Head>

			<Banner
				pageText='Tridev'
				headingText='Học lập trình cho người mới bắt đầu'
				desText='Nền tảng Tridev.io cung cấp cho bạn các khóa học,
                bài giảng, thông tin về lập trình một cách hoàn toàn
                miễn phí.'
				ctaText='Học ngay nào'
			/>
			<CatelogyTab />
			<CourseSection />
			<FeatureSection />
			<CatelogySection />
		</div>
	)
}
