import Head from "next/head"
import LoginForm from "../components/pages/auth/LoginForm"
import NotAllowAuth from "../HOC/NotAllowAuth"
import LayoutAuth from "../components/layouts/LayoutAuth"

function login() {
    return (
        <>
            <Head>
                <title>
                    Đăng nhập | Tridev.io - Học lập trình miễn phí | Học lập
                    trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
            <LayoutAuth>
                <LoginForm />
            </LayoutAuth>
        </>
    )
}

const CompideComponent = NotAllowAuth(login)

CompideComponent.getLayout = function getLayout(page) {
    return <div>{page}</div>
}

export default CompideComponent
