import Head from 'next/head'
import LayoutAuth from '../components/layouts/LayoutAuth'
import NotAllowIfAuthLayout from '../components/layouts/NotAllowIfAuthLayout'
import RegisterForm from '../components/pages/auth/RegisterForm'

function register() {
	return (
		<>
			<Head>
				<title>
					Đăng Ký | Tridev.io - Học lập trình miễn phí | Học lập trình
					cho người mới
				</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' type='image/png' href='/code.png' />
			</Head>

			<LayoutAuth>
				<RegisterForm />
			</LayoutAuth>
		</>
	)
}

register.getLayout = function getLayout(page) {
	return <NotAllowIfAuthLayout>{page}</NotAllowIfAuthLayout>
}

export default register
