import Head from "next/head"
import LayoutAuth from "../components/layouts/LayoutAuth"
import RegisterForm from "../components/pages/auth/RegisterForm"
import NotAllowAuth from "../HOC/NotAllowAuth"

function register() {
    return (
        <>
            <Head>
                <title>
                    Đăng Ký | Tridev.io - Học lập trình miễn phí | Học lập trình
                    cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>

            <LayoutAuth>
                <RegisterForm />
            </LayoutAuth>
        </>
    )
}

const CompideComponent = NotAllowAuth(register)

CompideComponent.getLayout = function getLayout(page) {
    return <div>{page}</div>
}

export default CompideComponent
