import { ChevronRightIcon } from "@chakra-ui/icons"
import {
    Box,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    Container,
    Grid,
    GridItem,
} from "@chakra-ui/react"
import Head from "next/head"
import Link from "next/link"
import CourseAside from "../../components/pages/course/CourseAside"
import CourseAsideMobile from "../../components/pages/course/CourseAsideMobile"
import CourseHeading from "../../components/pages/course/CourseHeading"
import CourseIntro from "../../components/pages/course/CourseIntro"
import CourseReview from "../../components/pages/course/CourseReview"
import CourseTab from "../../components/pages/course/CourseTab"

export default function CourseDetail() {
    return (
        <>
            <Head>
                <title>
                    khóa học | Tridev.io - Học lập trình miễn phí | Học lập
                    trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
            <Box pb='4' pt='8'>
                <Container maxW={[1024]}>
                    <Breadcrumb separator={<ChevronRightIcon />}>
                        <BreadcrumbItem>
                            <BreadcrumbLink href='/' as={Link}>
                                Trang chủ
                            </BreadcrumbLink>
                        </BreadcrumbItem>

                        <BreadcrumbItem>
                            <BreadcrumbLink href='/courses' as={Link}>
                                Khóa học
                            </BreadcrumbLink>
                        </BreadcrumbItem>

                        <BreadcrumbItem isCurrentPage>
                            <BreadcrumbLink href='#'>
                                Khóa học javascript nâng cao
                            </BreadcrumbLink>
                        </BreadcrumbItem>
                    </Breadcrumb>
                    {/* Container  */}
                    <Grid gridTemplateColumns='repeat(12, 1fr)' my='4' gap='4'>
                        <GridItem
                            // colSpan={["12", "12", "8"]}
                            p='4'
                            rounded='lg'
                            bg='white'
                            shadow='sm'
                            colSpan={["12", "12", "8"]}
                        >
                            {/* Heading  */}
                            <CourseHeading />
                            {/* Section only mobile */}
                            <CourseAsideMobile />
                            {/* Intro video or image */}
                            <CourseIntro />
                            {/* Tab */}
                            <CourseTab />
                            {/* Preview*/}
                            <CourseReview />
                        </GridItem>
                        <GridItem
                            colSpan={["12", "12", "4"]}
                            display={["none", "none", "block"]}
                        >
                            {/* Aside */}
                            <CourseAside />
                        </GridItem>
                    </Grid>
                </Container>
            </Box>
        </>
    )
}
