import Head from 'next/head'
import Banner from '../../components/pages/home/Banner'
import CategoryTab from '../../components/pages/home/CategoryTab'
import CourseSection from '../../components/pages/home/CourseSection'
export default function index() {
    return (
        <div>
            <Head>
                <title>
                    Danh sách các khóa học | Tridev.io - Học lập trình miễn phí
                    | Học lập trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
            <Banner
                bannerText='Course'
                headingText='Học lập trình cho người mới bắt đầu'
                desText='Nền tảng Tridev.io cung cấp cho bạn các khóa học,
                bài giảng, thông tin về lập trình một cách hoàn toàn
                miễn phí.'
                primaryColor='#f12711'
                secondaryColor='#f5af19'
            />

            <CategoryTab />
            <CourseSection />
        </div>
    )
}
