import Head from "next/head"
import Banner from "../../components/pages/home/Banner"
import CatelogyTab from "../../components/pages/home/CatelogyTab"
import CourseSection from "../../components/pages/home/CourseSection"
export default function index() {
    return (
        <div>
            <Head>
                <title>
                    Danh sách các khóa học | Tridev.io - Học lập trình miễn phí
                    | Học lập trình cho người mới
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' type='image/png' href='/code.png' />
            </Head>
            <Banner
                pageText='Course'
                headingText='Học lập trình cho người mới bắt đầu'
                desText='Nền tảng Tridev.io cung cấp cho bạn các khóa học,
                bài giảng, thông tin về lập trình một cách hoàn toàn
                miễn phí.'
                ctaText='Học ngay nào'
            />

            <CatelogyTab />
            <CourseSection />
        </div>
    )
}
